Feat/car classes
bwalczyk1/CarFleet pull request #2
Opened 2024-05-19 20:25 UTC by BuggedPotato

2024-05-19 21:38 UTC, bwalczyk1 requested changes

2024-05-19 21:38 UTC, bwalczyk1 commented on DeliveryCar.h
> +	virtual std::string getInfo() {
implementacja funkcji powinna być w pliku cpp

2024-05-19 21:38 UTC, bwalczyk1 commented on PassengerCar.h
> +	virtual std::string getInfo() {
tak samo jak wyżej

2024-05-19 22:44 UTC, BuggedPotato commented on DeliveryCar.h
> +	virtual std::string getInfo() {
poprawione

2024-05-19 22:44 UTC, BuggedPotato commented on PassengerCar.h
> +	virtual std::string getInfo() {
poprawione

2024-05-23 00:19 UTC, bwalczyk1 approved these changes

2024-05-23 00:19 UTC, merged